# Camel could also send message to Artemis
app:
  queue:
    consume: "jms:queue:Q.Test"
    produce: "jms:queue:RECEIVER_QUEUE"
spring:
  application:
    name: artemis-study
  artemis:
     # optional default
#    broker-url: tcp://localhost:61616
#    mode: native
    user: admin
    password: test
# Spring could send message directly to Artemis
jms:
  queue: Q.Test
