spring:
  application:
    name: artemis-study
  artemis:
     # optional default
#    broker-url: tcp://localhost:61616
#    mode: native
    user: admin
    password: test
jms:
  queue: Q.Test

# for camel
app:
  queue:
    consume: "jms:queue:CONSUMER_QUEUE"
    produce: "jms:queue:RECEIVER_QUEUE"
